### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by that-coder** [shomali11/util#1]
Hello @shomali11,
It's very useful util that you have written, but in this case how you are handling errors. For example, if func1 breaks I don't wanna execute the other two func.

```
func1 := func() {
    f(0)
}

func2 = func() {
    f(1)
}

func3 = func() {
    f(2)
}

Parallelize(func1, func2, func3)
```

**Comment by shomali11** [comment]
I updated the function signature to fail fast when a function fails.

This function is just a wrapper around my https://github.com/shomali11/parallelizer which has more features for better concurrency control if you are interested.
